cliente/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [#cambiar url logout
	url(r'^cliente/new', views.ClienteInsert.as_view(),
		name= "cliente_insert"),
	url(r'^cliente/list$', views.ClienteList.as_view(),
		name='cliente_list'),
	url(r'^cliente/edit(?P<pk>[0-9]+)/$',views.ClienteUpdate.as_view(),
		name='cliente_edit'),
	url(r'^cliente/delete(?P<pk>[0-9]+)/$', views.ClienteDelete.as_view(),
	 	name="cliente_delete"),
	url(r'^cliente/(?P<pk>[0-9]+)/$', views.cliente_detail, 
		name="cliente_detail"),




]

inventario/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [#cambiar url logout
	url(r'^inventario/new', views.InventarioInsert.as_view(), 
		name="inventario_insert"),
	url(r'^inventario/list$', views.InventarioList.as_view(), 
		name='inventario_list'),
	url(r'^inventario/edit(?P<pk>[0-9]+)/$', views.InventarioUpdate.as_view(), 
    	name='inventario_edit'),
	 url(r'^inventario/delete(?P<pk>[0-9]+)/$', views.InventarioDelete.as_view(),
	 	name="inventario_delete"),
	url(r'^inventario/(?P<pk>[0-9]+)/$', views.inventario_detail, 
		name="inventario_detail"),
]

plataforma/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('usuario.urls', namespace='usuario')),
    url(r'^', include('proveedor.urls', namespace='proveedor')),
    url(r'^', include('inventario.urls', namespace='inventario')),
    url(r'^', include('cliente.urls', namespace = 'cliente')),
    url(r'^', include('factura.urls', namespace = 'factura')),


]

proveedor/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [#cambiar url logout
	url(r'^proveedor/new', views.ProveedorInsert.as_view(),
	name="proveedor_insert"),
	url(r'^proveedor/list$', views.ProovedorList.as_view(),
		name='proveedor_list'),
	url(r'^proveedor/(?P<pk>[0-9]+)/$', views.proveedor_detail,
    	name="proveedor_detail"),
	url(r'^proveedor/edit(?P<pk>[0-9]+)/$',views.ProveedorUpdate.as_view(),
		name='proveedor_edit'),
	 url(r'^proveedor/delete(?P<pk>[0-9]+)/$', views.ProveedorDelete.as_view(),
	 	name="proveedor_delete"),
	url(r'^proveedor/buscar$', views.BuscarView.as_view(), name='buscar'),
	url(r'^proveedor/search$', views.search, name='search'),
	#url(r'^proveedor/ajax$', views.BusquedaAjax.as_view(), name='search_Ajax'),
	#url(r'^proveedor/busqueda', views.Busqueda.as_view(),
	#name="proveedor_ajax"),
	#url(r'^proveedor/busqueda_ajax/$',views.BusquedaAjax),
		#name = 'buscar_ajax'),

	#url(r'^proveedor/busqueda_ajax$', BusquedaAjax.as_view(), name='buscar_ajax'),
]

proveedor/models.py
from __future__ import unicode_literals

from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.

class Proveedor(models.Model):
	TIPO_CUENTA = (
		('corriente', 'Corriente'),
		('ahorros', 'Ahorros'),
		('recaudo','Recaudo'),
		)
	nit = models.CharField(max_length=15, unique=True)
	nombreEmpresa = models.CharField(max_length=45)
	nombreRepresentante = models.CharField(max_length=45)
	apellidoRepresentante = models.CharField(max_length=45)
	telefonoUno = PhoneNumberField(default='+570387260001')
	telefonoDos = PhoneNumberField(default='+573040000001')
	correo = models.EmailField(max_length=100, blank=True, null=True)
	sitioWeb = models.CharField(max_length=100, blank=True, null=True)
	ciudad = models.CharField(max_length=25)
	direccion = models.CharField(max_length=45)
	banco = models.CharField(max_length=45)
	tipoCuenta = models.CharField(choices=TIPO_CUENTA ,max_length=25)
	numeroCuenta = models.CharField(max_length=15, unique=True)

	def __unicode__(self):
		return self.nombreEmpresa

proveedor/views.py
from django.shortcuts import render, redirect,get_object_or_404

from .models import Proveedor
#importar http
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
#Vistas
from django.views.generic import ListView, TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    UpdateView,
    CreateView,
    DeleteView
    )
from django.core.urlresolvers import reverse_lazy

#Permisos
from django.contrib.auth.mixins import (
    LoginRequiredMixin, PermissionRequiredMixin)
from django.contrib.auth.decorators import login_required


#---------------------Proveedor ---------------------------------
class ProveedorInsert(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
	permission_required = ('proveedor.add_proveedor')
	model = Proveedor
	success_url = reverse_lazy('proveedor:proveedor_list')
	fields = ['nit','nombreEmpresa','nombreRepresentante',
	'apellidoRepresentante','telefonoUno','telefonoDos',
	'correo','sitioWeb','ciudad','direccion','banco',
	'tipoCuenta','numeroCuenta',]

class ProovedorList(LoginRequiredMixin, PermissionRequiredMixin, ListView):#,
    permission_required= ('proveedor.add_proveedor')
    model = Proveedor
    context_object_name = 'proveedores'

class ProveedorUpdate(LoginRequiredMixin,PermissionRequiredMixin, UpdateView):
    permission_required = ('proveedor.change_proveedor')
    model = Proveedor
    success_url = reverse_lazy('proveedor:proveedor_list')
    fields = ['nit','nombreEmpresa','nombreRepresentante',
              'apellidoRepresentante','telefonoUno','telefonoDos',
              'correo','sitioWeb','ciudad','direccion','banco',
              'tipoCuenta','numeroCuenta',]


class ProveedorDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required= ('proveedor.delete_proveedor')
    model = Proveedor
    success_url = reverse_lazy('proveedor:proveedor_list')

@login_required()
def proveedor_detail(request, pk):
    #capturar id de reservaciones
    proveedor = get_object_or_404(Proveedor, pk=pk)
    #hacer iterable la relacion ManyToMany con el all
    #resources = reservation.resource.all()
    template = loader.get_template('proveedor/proveedor_detail.html')
    context = {
        'proveedor' : proveedor
    }
    return HttpResponse(template.render(context, request))


class BuscarView(LoginRequiredMixin, TemplateView):
    #funcion que se ejecuta con boton tiene Metodo Post
    def post(self, request, *args, **kwargs):
        buscar = request.POST['busqueda']
        print buscar
        #nombreEmpresa__ con dos rayas al piso para acceder al atributo
        busqueda = Proveedor.objects.filter(nombreEmpresa__contains=buscar)
        if busqueda:
            print ("ha preuntado por un proveedor")
            print busqueda
        else:
            busqueda = Proveedor.objects.filter(nombreRepresentante__contains=buscar)
            print busqueda
            print ("ha preuntado por un represntante")
        return render(request, 'proveedor/proveedor_buscar.html',
            {'busqueda' : busqueda, 'proveedor':True})
        #provedor nombre del model
        #busqueda el filter

import json
#select * from proveedor where nombreEmpresa like '%Dev'
#proveedores = Proveedor.objects.filter(nombreEmpresa__startswhit=busqueda)

@login_required()
def search(request):
    busqueda = request.GET.get('nombreEmpresa')#diccionario
    proveedores = Proveedor.objects.filter(nombreEmpresa__contains=busqueda)
    proveedores = [ proveedor_serializer(proveedor) for proveedor in proveedores]# Lista de diccionarios
    return HttpResponse(json.dumps(proveedores), content_type = 'aplication/json')

@login_required()
def proveedor_serializer(proveedor):
    return {'id':proveedor.id,'nit':proveedor.nit, 'nombreEmpresa':proveedor.nombreEmpresa, 'nombreRepresentante': proveedor.nombreRepresentante}



"""
class Busqueda(ListView):
    model = Proveedor
    #Template_name = 'proveedor/proveedor_busquedaAjax.html'
    context_object_name = 'proveedores'


from django.core import serializers

def BusquedaAjax (request):
    print "fuera"
    if request.method == 'GET':
        print 'hola'



class BusquedaAjax(TemplateView):
    print "hola"
    def get(self, request, *args, **kwargs):
        print "En Get"
        id_proveedor = request.GET['id']
        print id_proveedor


        proveedor = Proveedor.objects.filter(proveedor__id = id_proveedor)
        data = serializers.serialize('json', proveedor,
            fields=('nombreEmpresa','nombreRepresentante'))
        return HttpResponse(data, mimetype='application/json')
        """

templates/proveedor/proveedor_buscar.html
{% extends "system_index.html" %}



{% block system_Contable %}
	

			

	<a href="{% url 'proveedor:proveedor_list'%}"><span class="icon fa-chevron-left" ></span></a></br></br>


	<table id="example1" class="table table-bordered table-striped">
    
    <thead>
        <tr>                                 
            <th>Empresa</th> 
            <th>Telefono</th>                              
            <th>Ciudad</th>
            <th>Dirección</th>
            <th></th>  
                                
        </tr>
    </thead>
    <tbody>
    	{% if proveedor %}
	    	{% for proveedor in busqueda %}
	    		<tr>
	    			<td>{{proveedor.nombreEmpresa}}</td>
	    			<td>{{proveedor.telefonoUno}}</td>
	    			<td>{{proveedor.ciudad}}</td>
	    			<td>{{proveedor.direccion}}</td>
					<td><a href="{% url 'proveedor:proveedor_detail' proveedor.id %}"><span class="icon fa-eye "></span></a>
						<a href="{% url 'proveedor:proveedor_edit' proveedor.id %}"><span class="icon fa-pencil-square-o"></span></a>
					</td>
	    		</tr>
	    	{% endfor %}
	    {% endif %}
    </tbody>	

</table>






{% endblock %}

templates/proveedor/proveedor_confirm_delete.html
{% extends "system_index.html" %}

{% block system_Contable %}
<a href="{%url 'inventario:inventario_list' %}"><span class="icon fa-arrow-left "></span></a>
<form method="post">
	{% csrf_token %}
    ¿Estás seguro que deseas borrar "{{ object }}"?
    <input type="submit" value="Borrar" />
</form>

{%endblock%}

templates/proveedor/proveedor_detail.html
{% extends "system_index.html" %}

{% block system_Contable %}
<a href="{%url 'proveedor:proveedor_list' %}"><span class="icon fa-arrow-left "></span></a>
	<ul>
		<li><b>Nit: </b>{{proveedor.nit}}</li>
		<li><b>Empresa: </b>{{proveedor.nombreEmpresa}}</li>
		<li><b>Representante: </b>{{proveedor.nombreRepresentante}} {{proveedor.apellidoRepresentante}}</li>
		<li><b>Telefonos: </b>{{proveedor.telefonoUno}}  |||  {{proveedor.telefonoDos}}</li>
		<li><b>Email: </b>{{proveedor.correo}}</li>
		<li><b>Sitio Web: </b>{{proveedor.sitioWeb}}</li>
		<li><b>Ciudad: </b>{{proveedor.ciudad}}</li>
		<li><b>Dirección: </b>{{proveedor.direccion}}</li>
		<li><b>Banco: </b>{{proveedor.banco}}</li>
		<li><b>Tipo de cuenta: </b>{{proveedor.tipoCuenta}}</li>
		<li><b>Numero de cuenta: </b>{{proveedor.numeroCuenta}}</li>
	</ul>
{%endblock%}

templates/proveedor/proveedor_form.html
{% extends "system_index.html" %}

{% block system_Contable %}
<a href="{%url 'proveedor:proveedor_list' %}"><span class="icon fa-arrow-left "></span></a>
<form method="post">
	<header>
        <h2>Proveedor </h2>
    </header>
   
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" />
</form>
{%endblock%}

templates/proveedor/proveedor_list.html
{% extends "system_index.html" %}

{% block system_Contable %}


<!--Busqueda de reservacion hacer una clase para ese search-->
    <div class="busqueda">
        <form class="navbar-search pull-left" method="POST" action="{%url 'proveedor:buscar'%}">{% csrf_token%}
            <input type="text" name="busqueda" class="search-query" placeholder="Buscar">
            <div class="btn-group">
                <button class="btn btn-primary" type="submit"><i class="icon fa-search"></i></button>
            </div>
        </form>
    </div>
<!--Edn Busqueda de reservacion-->
</BR></BR></BR></BR></BR>



<table id="example1"  >
    
    <thead>
        <tr>                                 
            <th>Empresa</th> 
            <th>Telefono</th>                              
            <th>Ciudad</th>
            <th>Dirección</th>
            <th></th>  
                                
        </tr>
    </thead>
    <tbody id="datosCa">
    	{% for pr in proveedores %}
    		<tr>
    			<td>{{pr.nombreEmpresa}}</td>
    			<td>{{pr.telefonoUno}}</td>
    			<td>{{pr.ciudad}}</td>
    			<td>{{pr.direccion}}</td>
				<td>
                    <a href="{% url 'proveedor:proveedor_detail' pr.id %}"><span class="icon fa-eye "></span></a>
					<a href="{% url 'proveedor:proveedor_edit' pr.id %}"><span class="icon fa-pencil-square-o"></span></a>
                    <a href="{% url 'proveedor:proveedor_delete' pr.id %}"><span class="icon fa-trash"></span></a>
				</td>
    		</tr>
    	{% endfor %}
    </tbody>	

</table>



<!-- Prueba de Ajax -->
<form method="GET" action="{% url 'proveedor:search'%}" id="search-proveedor">
    <div>
        <input type="text" name="nombreEmpresa">
        <input type="submit" value="Buscar">
    </div>
</form>

<!--
<div id="datos">
    
</div>
-->
<table id="datos">
    <thead>
        <tr>
            <th>Nit</th>                             
            <th>Empresa</th> 
            <th>Representante</th>                       
        </tr>
    </thead>
    <tbody id="datosC">
        <tr>
            
        </tr>
    </tbody>
</table>



{%endblock%}

templates/proveedor/proveedor_listpruebajax.html
{% extends "system_index.html" %}

{% block system_Contable %}

	<select>

		<option>Elije un proveedor</option>
		{% for pr in proveedores %}
			<option value="{{pr.id}}">{{pr.nombreEmpresa}}</option>
			
		{% endfor %}
	</select>

	<div id="datos">
		
	</div>

{% endblock %}



{% block js %}
	<script >
		$('select').on('change',inicio);
		function inicio(){
			var id = $(this).val();
			$.ajax({
				data: {'id':id},
				url: '/proveedor/busqueda_ajax/',
				type: 'get',
				
				/*success: function(data){
					console.log(data)
					/*var html=""
					for(var i = 0; i<data.length; i++){
						html += '<ul><li>'+data[i].fields.nombreEmpresa+'</li><li>'+data[i].fields.nombreRepresentante+'</li></lu>'
					}
					$('#datos').html(html);*/
				/*}*/ 
			});
		}
	</script>

{% endblock %}