cliente/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [#cambiar url logout
	url(r'^cliente/new', views.ClienteInsert.as_view(),
		name= "cliente_insert"),
	url(r'^cliente/list$', views.ClienteList.as_view(),
		name='cliente_list'),
	url(r'^cliente/edit(?P<pk>[0-9]+)/$',views.ClienteUpdate.as_view(),
		name='cliente_edit'),
	url(r'^cliente/delete(?P<pk>[0-9]+)/$', views.ClienteDelete.as_view(),
	 	name="cliente_delete"),
	url(r'^cliente/(?P<pk>[0-9]+)/$', views.cliente_detail, 
		name="cliente_detail"),




]

factura/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [#cambiar url logout
    url(r'^factura$',
    	TemplateView.as_view(template_name="factura/factura_index.html"),
    	name="factura"),
    url(r'^factura/new', views.FacturaInsert.as_view(),
    	name="factura_insert"),
    url(r'^factura/list$',views.FacturaList.as_view(),
        name='factura_list'),
    url(r'^factura/edit(?P<pk>[0-9]+)/$',views.FacturaUpdate.as_view(),
    	name='factura_edit'),
    url(r'^factura/(?P<pk>[0-9]+)/$', views.factura_detail,
		name="factura_detail"),
    url(r'^factura/detalle', views.DetalleFacturaInsert.as_view(),
    	name="detalle_factura_insert"),
    url(r'^factura/reporteAll', views.Generar_pdf, name='reporte_Facturas'),
    url(r'^factura/Pdf_Factura', views.PdfFactura.as_view(),
       name='reporte_Detalle_Factura'),
    #prueba de reporte estatico con reportLab
    #url(r'^factura/report/$', views.report),
]

plataforma/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('usuario.urls', namespace='usuario')),
    url(r'^', include('proveedor.urls', namespace='proveedor')),
    url(r'^', include('inventario.urls', namespace='inventario')),
    url(r'^', include('cliente.urls', namespace = 'cliente')),
    url(r'^', include('factura.urls', namespace = 'factura')),


]

factura/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from cliente.models import Cliente
from inventario.models import Inventario
import decimal
from django.db.models import signals
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect
from django.db import IntegrityError
import usuario.urls
# from django.core.exceptions import IntegrityError
class Factura(models.Model):
	FORMA_PAGO= (
		('efectivo', 'Efectivo'), ('cheque', 'Cheque'),
		('tarjeta debito', 'Tarjeta debito'), ('tarjeta credito', 'Tarjeta credito'),
		('venta a credito','Venta a credito'), ('bono','Bono'),
		('vale','Vale'), ('otros','Otros'),
		)
	serie = models.AutoField(primary_key=True, auto_created=True, serialize=False)#codigo de factura
	maquina = models.CharField(max_length=20)#N Seriemaquina
	fecha = models.DateField(auto_now_add=True)#fecha de Venta
	vendedor = models.ForeignKey(User)
	cliente = models.ForeignKey(Cliente)
	formaPago = models.CharField(choices=FORMA_PAGO ,
		max_length=50, verbose_name='forma de pago')
	iva = models.DecimalField(max_digits=6, decimal_places=2, default=0,
		null=True, blank=True)
	total = models.DecimalField(max_digits=8, default=0,
		decimal_places=2, null=True, blank=True)
	def __str__(self):
		return str(self.serie)

"""	def save(self, *args, **kwargs):
		self.iva = 0
		self.total = 0
		super(Factura, self).save(*args, **kwargs)"""

class DetalleFactura(models.Model):
	factura =models.ForeignKey(Factura, on_delete=models.CASCADE)
	producto = models.ForeignKey(Inventario)
	descripcion = models.CharField(max_length=45)
	precio = models.DecimalField(max_digits=7, decimal_places=2)
	cantidad = models.PositiveSmallIntegerField()
	valorIva = models.DecimalField(max_digits=6, decimal_places=2)
	subtotal = models.DecimalField(max_digits=6, decimal_places=2)

	def __unicode__(self):
		return self.descripcion

# en ./manage.py shell
# from inventario.models import Inventario
# >>> producto = "cuchara soprera Tami"
# >>> precio = Inventario.objects.get(elemento=producto)
# >>> precio.cantidad
# 30


	def save(self, *args, **kwargs):
		try:
			consultaPrecio = Inventario.objects.get(elemento=self.producto)
			self.precio = round(float(consultaPrecio.valorVenta))
			self.valorIva = round(float(consultaPrecio.valorIva)*self.cantidad)
			self.subtotal = round(float(self.precio)*self.cantidad)
			consultaPrecio.cantidad -= self.cantidad
			consultaPrecio.save()
			consultaFactura = Factura.objects.get(serie = str(self.factura))
			consultaFactura.iva = round(float(consultaFactura.iva)) + round(float(self.valorIva))
			consultaFactura.total = round(float(consultaFactura.total))+ round(float(self.subtotal))
			consultaFactura.save()
			super(DetalleFactura, self).save(*args, **kwargs)
		except IntegrityError :
			return redirect('factura:factura_insert')
		else:
			pass

		super(DetalleFactura, self).save(*args, **kwargs)



	# def updateStock(sender,instance, **kwargs):
	# 	instance.inventario.cantidad -= instance.cantidad
	# 	print(instance.inventario.cantidad)
	# 	instance.inventario.save()
	#
	# def save(self, *args, **kwargs):
	# 	self.precio = round(float(instance.inventario.valorVenta))
	# 	self.valorIva = round(float(instance.inventario.valorIva) * self.cantidad)
	# 	super(DetalleFactura, self).save(*args, **kwargs)
	#
	# 	signals.post_save.connect(update_stock, sender=DetalleFactura, dispatch_uid="update_stock_count")

factura/views.py
#-*- coding: utf-8 -*-

from django.shortcuts import render, redirect,get_object_or_404

#importar http
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader, Context
#Vistas
from django.views.generic import ListView, TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    UpdateView,
    CreateView,
    DeleteView
    )
from django.contrib.auth.models import User
from inventario.models import Inventario
from .models import Factura, DetalleFactura
from django.core.urlresolvers import reverse_lazy
#mixins
from django.contrib.auth.mixins import(
    LoginRequiredMixin, PermissionRequiredMixin)
from django.contrib.auth.decorators import (
    login_required, permission_required)
#pdf Dionicio
import datetime
#por defecto se instala html5lib==0.999999999
#para que funciones pip install html5lib==1.0b8
import xhtml2pdf.pisa as pisa
import cStringIO as StringIO
from django import http
import cgi


def buscarProducto(request):
    busqueda = request.GET.get('serie')
    producto = Inventario.objects.filter(codigo=busqueda)
    data = serializers.serialize(
        'json', producto, fields=('codigo','elemento', 'cantidad',
                                  'valorIva', 'valorVenta'))
    return HttpResponse(data, content_type='application/json')

class FacturaInsert(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = ('factura.add_factura')
    model = Factura
    success_url = reverse_lazy('factura:factura_list')
    fields = ['maquina','cliente','formaPago',]
    def form_valid(self, form):
        form.instance.vendedor = self.request.user
        return super(FacturaInsert, self).form_valid(form)

class FacturaList(LoginRequiredMixin, ListView):
    #permission_required = ('factura.add_factura')
    model = Factura
    context_object_name = 'facturas'

class FacturaUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = ('factura.change_factura')
    model = Factura
    success_url = reverse_lazy('factura:factura_list')
    fields = ['maquina', 'cliente', 'formaPago',]

@login_required()
@permission_required('factura.add_factura')
def factura_detail(request, pk):
    factura = get_object_or_404(Factura, pk=pk)
    template = loader.get_template('factura/factura_detail.html')
    context = {
        'factura' : factura
    }
    return HttpResponse(template.render(context, request))

#Funciones de Creacion de PDF

#@login_required()
#@permission_required('factura.add_factura')
def write_pdf(template_src, context_dict):
    template = loader.get_template(template_src)
    context = Context(context_dict)
    html = template.render(context)
    result = StringIO.StringIO()
    pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("utf-8")), result)
    if not pdf.err:
        return http.HttpResponse(result.getvalue(),
                                 content_type = 'application/pdf')
    return http.HttpResponse('ocurrio un error al generar el reporte %s'% cgi.escape(html))

#@login_required()
#@permission_required('factura.add_factura')
def Generar_pdf(request):
    ventas = Factura.objects.all()
    return write_pdf('factura/factura_all.html',
                     {'pagesize':'legal', 'ventas':ventas})
#Final de Funciones de Creacion de PDF

class PdfFactura(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    permission_required = ('factura.add_factura')
    def post(self, request, *args, **kwargs):
        buscar = request.POST['busqueda']
        print(buscar)
        ventas = DetalleFactura.objects.filter(factura=buscar).order_by("-producto")
        datoFactura = Factura.objects.filter(serie=buscar)
        return write_pdf('factura/factura_Detalle.html',
                         {'pagesize':'A4', 'ventas':ventas,'datoFactura':datoFactura})





class DetalleFacturaInsert(LoginRequiredMixin, CreateView):
    model = DetalleFactura
    success_url = reverse_lazy('factura:factura_list')
    fields = ['factura', 'producto', 'descripcion', 'cantidad']

#funcion de ver el contenido de la factura por busqueda de serie
# class BuscarFactura(TemplateView)
#     def post(self, request, *args, **kwargs):
#         buscar = request.POST['busqueda']
#         print buscar

"""
#pdf
import os
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.styles import getSampleStyleSheet, TA_CENTER
from reportlab.platypus.paragraph import Paragraph
from reportlab.platypus import Table, TableStyle
from reportlab.lib.pagesizes import A4, cm
from reportlab.lib import colors
"""

"""
# class Generar_pdf(TemplateView):
#     def post(self, request, *args, **kwargs):
#         buscar = request.POST['busqueda']
#         ventas = Factura.objects.all()
#         return write_pdf('factura/factura_all.html',
#                          {'pagesize':'legal', 'ventas':ventas})

# Reporte Dinamico
class ReporteView(TemplateView):
    def post(self, request, *args, **kwargs):
        buscar = request.POST['busqueda']
        ventas = Factura.objects.all()
        return render(request, 'factura/factura_all.html',
                      {'ventas':ventas, 'factura':True})



#Report statico Reportlab
def report(request):
    #sabe que la funcion va responder un pdf
    response = HttpResponse(content_type='application/pdf')
    #se agrega el nombre de archivo y el conten-disposition para que se puyeda descargar del navegador
    response ['Content-Disposition'] = 'attachment; filename=Prueba_venta.pdf'
    #buffer de datos
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    #Header
    c.setLineWidth(.3)
    c.setFont('Helvetica', 22)
    # c.drawString(Izq_der, Abajo_arriba, 'texto')
    c.drawString(30, 750, 'Mayorista')
    c.setFont('Helvetica', 12)
    c.drawString(30,735, 'Report')
    c.setFont('Helvetica-Bold', 12)
    #fecha = datetime.datetime.now()
    c.drawString(480, 750, '20/10/2017' )
    c.line(460,747,560,747)

    #contenido estatico de tabla
    students = [{'#':'1', 'name':'Romario', 'b1':'4.5', 'b2':'4.8', 'b3':'5.0', 'total':'4.8'},
                {'#':'2', 'name':'Masha', 'b1':'3.0', 'b2':'3.8', 'b3':'3.5', 'total':'3.6'}]

    #tabla header
    #carga todos los estilos de la tabla
    styles = getSampleStyleSheet()
    styleBH = styles["Normal"]
    styleBH.alignment = TA_CENTER
    styleBH.fontSize = 10

    #Titulos de columna
    numero = Paragraph('''#''', styleBH)
    alumno = Paragraph(''' Alumno ''', styleBH)
    b1 = Paragraph(''' BIM1 ''', styleBH)
    b2 = Paragraph(''' BIM2 ''', styleBH)
    b3 = Paragraph(''' BIM3 ''', styleBH)
    total = Paragraph(''' TOTAL ''', styleBH)

    data = []
    #lista de la tabla con si
    #data.append = [[numero]]

    #tabla contenido
    styleN = styles["BodyText"]
    styleN.alignment = TA_CENTER
    styleN.fontSize = 7


    high = 650
    for student in students:
        this_student = [student['#'], student['name'], student['b1'], student['b2'], student['b3'], student['total']]
        data.append(this_student)
        high = high -18

    #escribir la tabla
    width, heigth = A4
    table = Table(data, colWidths = [1.9*cm, 9.5*cm, 1.9*cm, 1.9*cm, 1.9*cm, 1.9*cm])
    #Grilla de la tabla
    table.setStyle(TableStyle([
        ('INNERGRID', (0,0), (-1,-1), 0.25, colors.black),
        ('BOX',(0,0), (-1, -1), 0.25, colors.black), ]))

    #pdf size encapsularlo en el tamaño del A4 o tamaño de pagina
    table.wrapOn(c, width, heigth)
    table.drawOn(c, 30, high)
    c.showPage() #save page


    #guardar pdf
    c.save()
    #obtener valores de BytesIO del buffer y escribir en response
    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)
    #con el return descraga pdf
    return response
"""

templates/factura/detallefactura_form.html
{%extends "system_index.html"%}

{% block system_Contable %}

<form method="post">
<a href="{%url 'factura:factura_list' %}"><span class="icon fa-arrow-left "></span></a>

	<header>
				<h2>Detalles</h2>
	</header>

		{% csrf_token %}
		{{ form.as_p }}
		



    <input type="submit" value="Submit" />
</form>


{% endblock %}

templates/factura/factura_Detalle.html
<\<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Reporte de facturas</title>
	</head>
	<body>
    {% for algo in datoFactura %}
		<div id="headerContent">
		    <center> <h1>EL MAYORISTA</h1>
		    <h3>Direccion: Cra 10 # , Chiquinquirá, Boyacá</h3>
		    <h3>Télefono: </h3>
		    <h3>NIT: </h3>
        <h3>Maquina: {{algo.maquina}} </h3>
        <h3>Fecha: {{algo.fecha}}</h3>
        <h3>Vendedor: {{algo.vendedor}} </h3>
        <h3>Cliente: {{algo.cliente}} </h3>
        <h3>Forma de pago {{algo.formaPago}} </h3>
        <h3> </h3>
        <h3> </h3>
		</div>
          </br><center> <h2> FACTURA DE VENTA {{algo.serie}} </h2>
  {% endfor %}

		<table id="example1" class="table table-bordered table-striped">
	    <thead>
	        <tr>
	            <th style="border:1px solid black; padding: 2px;">producto</th>
	            <th style="border:1px solid black; padding: 2px;">precio</th>
	            <th style="border:1px solid black; padding: 2px;">cantidad</th>
	            <th style="border:1px solid black; padding: 2px;">valorIva</th>
              <th style="border:1px solid black; padding: 2px;">subtotal</th>
	        </tr>
	    </thead>
	    <tbody>
		    	{% for factura in ventas %}
		    		<tr>
		    			<td style="border:1px solid black; padding: 2px;">{{factura.producto}}</td>
		    			<td style="border:1px solid black; padding: 2px;">{{factura.precio}}</td>
		    			<td style="border:1px solid black; padding: 2px;">{{factura.cantidad}}</td>
		    			<td style="border:1px solid black; padding: 2px;">{{factura.valorIva}}</td>
              <td style="border:1px solid black; padding: 2px;">{{factura.subtotal}}</td>
		    		</tr>
		    	{% endfor %}
	    </tbody>
      {% for algo in datoFactura %}
      <thead>
	        <tr>
            <th></th><th></th><th></th>
	          <th style="border:1px solid black; padding: 2px;">Total Iva</th>
            <th style="border:1px solid black; padding: 2px;">{{algo.iva}}</th>
	        </tr>
	    </thead>
      <thead>
          <tr>
            <th></th><th></th><th></th>
            <th style="border:1px solid black; padding: 2px;">Total</th>
            <th style="border:1px solid black; padding: 2px;">{{algo.total}}</th>
          </tr>
      </thead>
      {% endfor %}
	</table>

	</body>
</html>

templates/factura/factura_all.html
<\<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Reporte de facturas</title>
	</head>
	<body>

		<div id="headerContent">
		    <center> <h1>EL MAYORISTA</h1>
		    <h3>Direccion: Cra 10 # , Chiquinquirá, Boyacá</h3>
		    <h3>Télefono: </h3>
		   <h3>NIT: </h3>
		   </div>
		 </br><center> <h2> REPORTE DE FACTURAS </h2>



		<table id="example1" class="table table-bordered table-striped">
	    <thead>
	        <tr>
	            <th style="border:1px solid black; padding: 2px;">Serie</th>
	            <th style="border:1px solid black; padding: 2px;">Maquina</th>
	            <th style="border:1px solid black; padding: 2px;">Vendedor</th>
	            <th style="border:1px solid black; padding: 2px;">Cliente</th>
	        </tr>
	    </thead>
	    <tbody>
	    	
		    	{% for factura in ventas %}
		    		<tr>
		    			<td style="border:1px solid black; padding: 2px;">{{factura.serie}}</td>
		    			<td style="border:1px solid black; padding: 2px;">{{factura.maquina}}</td>
		    			<td style="border:1px solid black; padding: 2px;">{{factura.vendedor}}</td>
		    			<td style="border:1px solid black; padding: 2px;">{{factura.cliente}}</td>

		    		</tr>
		    	{% endfor %}
		    {# {% endif %}#}
	    </tbody>
	</table>


	</body>
</html>

templates/factura/factura_detail.html
{% extends "system_index.html" %}

{% block system_Contable %}
<a href="{%url 'factura:factura_list' %}"><span class="icon fa-arrow-left "></span></a>
<h2>Factura : {{factura.serie}}</h2>
<ul>

	<li><b>Maquina: </b>{{factura.maquina}}</li>
	<li><b>Fecha: </b>{{factura.fecha}}</li>
	<li><b>Vendedor: </b>{{factura.vendedor}}</li>
	<li><b>Cliente: </b>{{factura.cliente}}</li>
	<li><b>Forma de pago: </b>{{factura.formaPago}}</li>
	<li><b>iva: </b>{{factura.iva}}</li>
	<li><b>Total: </b>{{factura.total}}</li>
</ul>
<a href="">New</a>
{%endblock%}

templates/factura/factura_form.html
{% extends "system_index.html" %}

{% block system_Contable %}
<form method="post">
<a href="{%url 'factura:factura_list' %}"><span class="icon fa-arrow-left "></span></a>
	<header>
        <h2>Factura </h2>
    </header>
   
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" />
</form>
{%endblock%}

templates/factura/factura_index.html
{% extends "system_index.html" %}


{% block system_Contable %}

<h2>Factura</h2>

<form>
	<input type="text" name="" placeholder="">
</form>




{%endblock %}

templates/factura/factura_list.html
{% extends "system_index.html" %}

{% block system_Contable %}

<!--Boton descargar pdf todas las facturas-->
    <div class="pdf">
        <form class="navbar-search pull-left" method="POST" action="{%url 'factura:reporte_Facturas'%}">{% csrf_token%}
          <center><h4>Reporte de ventas</h4>
          <button class="btn btn-primary" type="submit"><i class="icon fa-file-pdf-o"></i></button>
        </form>
    </div>
    </BR></BR></BR>
<!--end descargar pdf todas las facturas-->


<!--Busqueda de detalles de factura-->
    <div class="busqueda">
        <form class="navbar-search pull-left" method="POST" name="detalle_factura" action="{%url 'factura:reporte_Detalle_Factura'%}">{% csrf_token%}
            <input title="se requiere numero" type="number" name="busqueda" class="search-query" placeholder="Buscar factura"  required>
            <div class="btn-group">
                <button class="btn btn-primary" type="submit"><i class="icon fa-file-pdf-o"></i></button>
            </div>
        </form>
    </div>

<!--Edn Busqueda de detalles de factura-->
</BR></BR></BR></BR>

<table id="example1" class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Factura</th>
            <th>Fecha</th>
            <th>Vendedor</th>
            <th>Cliente</th>
            <th>Iva</th>
            <th>Total</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    	{% for pr in facturas %}
    		<tr>
    			<td>{{pr.serie}}</td>
    			<td>{{pr.fecha}}</td>
    			<td>{{pr.vendedor}}</td>
    			<td>{{pr.cliente}}</td>
    			<td>{{pr.iva}}</td>
    			<td>{{pr.total}}</td>
				<td><a href="{% url 'factura:factura_detail' pr.serie %}"><span class="icon fa-eye "></span></a>
				<a href="{% url 'factura:factura_edit' pr.serie%}"><span class="icon fa-pencil-square-o"></span></a>
    		</tr>
    	{% endfor %}
    </tbody>

</table>

{%endblock%}