cliente/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [#cambiar url logout
	url(r'^cliente/new', views.ClienteInsert.as_view(),
		name= "cliente_insert"),
	url(r'^cliente/list$', views.ClienteList.as_view(),
		name='cliente_list'),
	url(r'^cliente/edit(?P<pk>[0-9]+)/$',views.ClienteUpdate.as_view(),
		name='cliente_edit'),
	url(r'^cliente/delete(?P<pk>[0-9]+)/$', views.ClienteDelete.as_view(),
	 	name="cliente_delete"),
	url(r'^cliente/(?P<pk>[0-9]+)/$', views.cliente_detail, 
		name="cliente_detail"),




]

factura/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [#cambiar url logout
    url(r'^factura$',
    	TemplateView.as_view(template_name="factura/factura_index.html"),
    	name="factura"),
    url(r'^factura/new', views.FacturaInsert.as_view(),
    	name="factura_insert"),
    url(r'^factura/list$',views.FacturaList.as_view(),
        name='factura_list'),
    url(r'^factura/edit(?P<pk>[0-9]+)/$',views.FacturaUpdate.as_view(),
    	name='factura_edit'),
    url(r'^factura/(?P<pk>[0-9]+)/$', views.factura_detail,
		name="factura_detail"),
    url(r'^factura/detalle', views.DetalleFacturaInsert.as_view(),
    	name="detalle_factura_insert"),
    url(r'^factura/reporteAll', views.Generar_pdf, name='reporte_Facturas'),
    url(r'^factura/Pdf_Factura', views.PdfFactura.as_view(),
       name='reporte_Detalle_Factura'),
    #prueba de reporte estatico con reportLab
    #url(r'^factura/report/$', views.report),
]

inventario/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [#cambiar url logout
	url(r'^inventario/new', views.InventarioInsert.as_view(), 
		name="inventario_insert"),
	url(r'^inventario/list$', views.InventarioList.as_view(), 
		name='inventario_list'),
	url(r'^inventario/edit(?P<pk>[0-9]+)/$', views.InventarioUpdate.as_view(), 
    	name='inventario_edit'),
	 url(r'^inventario/delete(?P<pk>[0-9]+)/$', views.InventarioDelete.as_view(),
	 	name="inventario_delete"),
	url(r'^inventario/(?P<pk>[0-9]+)/$', views.inventario_detail, 
		name="inventario_detail"),
]

plataforma/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('usuario.urls', namespace='usuario')),
    url(r'^', include('proveedor.urls', namespace='proveedor')),
    url(r'^', include('inventario.urls', namespace='inventario')),
    url(r'^', include('cliente.urls', namespace = 'cliente')),
    url(r'^', include('factura.urls', namespace = 'factura')),


]

proveedor/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [#cambiar url logout
	url(r'^proveedor/new', views.ProveedorInsert.as_view(),
	name="proveedor_insert"),
	url(r'^proveedor/list$', views.ProovedorList.as_view(),
		name='proveedor_list'),
	url(r'^proveedor/(?P<pk>[0-9]+)/$', views.proveedor_detail,
    	name="proveedor_detail"),
	url(r'^proveedor/edit(?P<pk>[0-9]+)/$',views.ProveedorUpdate.as_view(),
		name='proveedor_edit'),
	 url(r'^proveedor/delete(?P<pk>[0-9]+)/$', views.ProveedorDelete.as_view(),
	 	name="proveedor_delete"),
	url(r'^proveedor/buscar$', views.BuscarView.as_view(), name='buscar'),
	url(r'^proveedor/search$', views.search, name='search'),
	#url(r'^proveedor/ajax$', views.BusquedaAjax.as_view(), name='search_Ajax'),
	#url(r'^proveedor/busqueda', views.Busqueda.as_view(),
	#name="proveedor_ajax"),
	#url(r'^proveedor/busqueda_ajax/$',views.BusquedaAjax),
		#name = 'buscar_ajax'),

	#url(r'^proveedor/busqueda_ajax$', BusquedaAjax.as_view(), name='buscar_ajax'),
]

usuario/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [#cambiar url logout


    url(r'^$', TemplateView.as_view(template_name="index.html"), name="index"),
    url(r'^login/$', views.authentication, name="authentication"),
    url(r'^plataforma', TemplateView.as_view(template_name="system_index.html"), name="system_index"),
    url(r'^perfil/new', views.PerfilInsert.as_view(), name="perfil_insert"),
    url(r'^perfil/list$',views.PerfilList.as_view(), name='perfil_list'),
    url(r'^perfil/edit(?P<pk>[0-9]+)/$',views.PerfilUpdate.as_view(),
    	name='perfil_edit'),
	#url(r'^perfil/logout/$', views.LogOut, name="logout"),
	url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name="logout"),



]

factura/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from cliente.models import Cliente
from inventario.models import Inventario
import decimal
from django.db.models import signals
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect
from django.db import IntegrityError
import usuario.urls
# from django.core.exceptions import IntegrityError
class Factura(models.Model):
	FORMA_PAGO= (
		('efectivo', 'Efectivo'), ('cheque', 'Cheque'),
		('tarjeta debito', 'Tarjeta debito'), ('tarjeta credito', 'Tarjeta credito'),
		('venta a credito','Venta a credito'), ('bono','Bono'),
		('vale','Vale'), ('otros','Otros'),
		)
	serie = models.AutoField(primary_key=True, auto_created=True, serialize=False)#codigo de factura
	maquina = models.CharField(max_length=20)#N Seriemaquina
	fecha = models.DateField(auto_now_add=True)#fecha de Venta
	vendedor = models.ForeignKey(User)
	cliente = models.ForeignKey(Cliente)
	formaPago = models.CharField(choices=FORMA_PAGO ,
		max_length=50, verbose_name='forma de pago')
	iva = models.DecimalField(max_digits=6, decimal_places=2, default=0,
		null=True, blank=True)
	total = models.DecimalField(max_digits=8, default=0,
		decimal_places=2, null=True, blank=True)
	def __str__(self):
		return str(self.serie)

"""	def save(self, *args, **kwargs):
		self.iva = 0
		self.total = 0
		super(Factura, self).save(*args, **kwargs)"""

class DetalleFactura(models.Model):
	factura =models.ForeignKey(Factura, on_delete=models.CASCADE)
	producto = models.ForeignKey(Inventario)
	descripcion = models.CharField(max_length=45)
	precio = models.DecimalField(max_digits=7, decimal_places=2)
	cantidad = models.PositiveSmallIntegerField()
	valorIva = models.DecimalField(max_digits=6, decimal_places=2)
	subtotal = models.DecimalField(max_digits=6, decimal_places=2)

	def __unicode__(self):
		return self.descripcion

# en ./manage.py shell
# from inventario.models import Inventario
# >>> producto = "cuchara soprera Tami"
# >>> precio = Inventario.objects.get(elemento=producto)
# >>> precio.cantidad
# 30


	def save(self, *args, **kwargs):
		try:
			consultaPrecio = Inventario.objects.get(elemento=self.producto)
			self.precio = round(float(consultaPrecio.valorVenta))
			self.valorIva = round(float(consultaPrecio.valorIva)*self.cantidad)
			self.subtotal = round(float(self.precio)*self.cantidad)
			consultaPrecio.cantidad -= self.cantidad
			consultaPrecio.save()
			consultaFactura = Factura.objects.get(serie = str(self.factura))
			consultaFactura.iva = round(float(consultaFactura.iva)) + round(float(self.valorIva))
			consultaFactura.total = round(float(consultaFactura.total))+ round(float(self.subtotal))
			consultaFactura.save()
			super(DetalleFactura, self).save(*args, **kwargs)
		except IntegrityError :
			return redirect('factura:factura_insert')
		else:
			pass

		super(DetalleFactura, self).save(*args, **kwargs)



	# def updateStock(sender,instance, **kwargs):
	# 	instance.inventario.cantidad -= instance.cantidad
	# 	print(instance.inventario.cantidad)
	# 	instance.inventario.save()
	#
	# def save(self, *args, **kwargs):
	# 	self.precio = round(float(instance.inventario.valorVenta))
	# 	self.valorIva = round(float(instance.inventario.valorIva) * self.cantidad)
	# 	super(DetalleFactura, self).save(*args, **kwargs)
	#
	# 	signals.post_save.connect(update_stock, sender=DetalleFactura, dispatch_uid="update_stock_count")

factura/views.py
#-*- coding: utf-8 -*-

from django.shortcuts import render, redirect,get_object_or_404

#importar http
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader, Context
#Vistas
from django.views.generic import ListView, TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    UpdateView,
    CreateView,
    DeleteView
    )
from django.contrib.auth.models import User
from inventario.models import Inventario
from .models import Factura, DetalleFactura
from django.core.urlresolvers import reverse_lazy
#mixins
from django.contrib.auth.mixins import(
    LoginRequiredMixin, PermissionRequiredMixin)
from django.contrib.auth.decorators import (
    login_required, permission_required)
#pdf Dionicio
import datetime
#por defecto se instala html5lib==0.999999999
#para que funciones pip install html5lib==1.0b8
import xhtml2pdf.pisa as pisa
import cStringIO as StringIO
from django import http
import cgi


def buscarProducto(request):
    busqueda = request.GET.get('serie')
    producto = Inventario.objects.filter(codigo=busqueda)
    data = serializers.serialize(
        'json', producto, fields=('codigo','elemento', 'cantidad',
                                  'valorIva', 'valorVenta'))
    return HttpResponse(data, content_type='application/json')

class FacturaInsert(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = ('factura.add_factura')
    model = Factura
    success_url = reverse_lazy('factura:factura_list')
    fields = ['maquina','cliente','formaPago',]
    def form_valid(self, form):
        form.instance.vendedor = self.request.user
        return super(FacturaInsert, self).form_valid(form)

class FacturaList(LoginRequiredMixin, ListView):
    #permission_required = ('factura.add_factura')
    model = Factura
    context_object_name = 'facturas'

class FacturaUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = ('factura.change_factura')
    model = Factura
    success_url = reverse_lazy('factura:factura_list')
    fields = ['maquina', 'cliente', 'formaPago',]

@login_required()
@permission_required('factura.add_factura')
def factura_detail(request, pk):
    factura = get_object_or_404(Factura, pk=pk)
    template = loader.get_template('factura/factura_detail.html')
    context = {
        'factura' : factura
    }
    return HttpResponse(template.render(context, request))

#Funciones de Creacion de PDF

#@login_required()
#@permission_required('factura.add_factura')
def write_pdf(template_src, context_dict):
    template = loader.get_template(template_src)
    context = Context(context_dict)
    html = template.render(context)
    result = StringIO.StringIO()
    pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("utf-8")), result)
    if not pdf.err:
        return http.HttpResponse(result.getvalue(),
                                 content_type = 'application/pdf')
    return http.HttpResponse('ocurrio un error al generar el reporte %s'% cgi.escape(html))

#@login_required()
#@permission_required('factura.add_factura')
def Generar_pdf(request):
    ventas = Factura.objects.all()
    return write_pdf('factura/factura_all.html',
                     {'pagesize':'legal', 'ventas':ventas})
#Final de Funciones de Creacion de PDF

class PdfFactura(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    permission_required = ('factura.add_factura')
    def post(self, request, *args, **kwargs):
        buscar = request.POST['busqueda']
        print(buscar)
        ventas = DetalleFactura.objects.filter(factura=buscar).order_by("-producto")
        datoFactura = Factura.objects.filter(serie=buscar)
        return write_pdf('factura/factura_Detalle.html',
                         {'pagesize':'A4', 'ventas':ventas,'datoFactura':datoFactura})





class DetalleFacturaInsert(LoginRequiredMixin, CreateView):
    model = DetalleFactura
    success_url = reverse_lazy('factura:factura_list')
    fields = ['factura', 'producto', 'descripcion', 'cantidad']

#funcion de ver el contenido de la factura por busqueda de serie
# class BuscarFactura(TemplateView)
#     def post(self, request, *args, **kwargs):
#         buscar = request.POST['busqueda']
#         print buscar

"""
#pdf
import os
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.styles import getSampleStyleSheet, TA_CENTER
from reportlab.platypus.paragraph import Paragraph
from reportlab.platypus import Table, TableStyle
from reportlab.lib.pagesizes import A4, cm
from reportlab.lib import colors
"""

"""
# class Generar_pdf(TemplateView):
#     def post(self, request, *args, **kwargs):
#         buscar = request.POST['busqueda']
#         ventas = Factura.objects.all()
#         return write_pdf('factura/factura_all.html',
#                          {'pagesize':'legal', 'ventas':ventas})

# Reporte Dinamico
class ReporteView(TemplateView):
    def post(self, request, *args, **kwargs):
        buscar = request.POST['busqueda']
        ventas = Factura.objects.all()
        return render(request, 'factura/factura_all.html',
                      {'ventas':ventas, 'factura':True})



#Report statico Reportlab
def report(request):
    #sabe que la funcion va responder un pdf
    response = HttpResponse(content_type='application/pdf')
    #se agrega el nombre de archivo y el conten-disposition para que se puyeda descargar del navegador
    response ['Content-Disposition'] = 'attachment; filename=Prueba_venta.pdf'
    #buffer de datos
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    #Header
    c.setLineWidth(.3)
    c.setFont('Helvetica', 22)
    # c.drawString(Izq_der, Abajo_arriba, 'texto')
    c.drawString(30, 750, 'Mayorista')
    c.setFont('Helvetica', 12)
    c.drawString(30,735, 'Report')
    c.setFont('Helvetica-Bold', 12)
    #fecha = datetime.datetime.now()
    c.drawString(480, 750, '20/10/2017' )
    c.line(460,747,560,747)

    #contenido estatico de tabla
    students = [{'#':'1', 'name':'Romario', 'b1':'4.5', 'b2':'4.8', 'b3':'5.0', 'total':'4.8'},
                {'#':'2', 'name':'Masha', 'b1':'3.0', 'b2':'3.8', 'b3':'3.5', 'total':'3.6'}]

    #tabla header
    #carga todos los estilos de la tabla
    styles = getSampleStyleSheet()
    styleBH = styles["Normal"]
    styleBH.alignment = TA_CENTER
    styleBH.fontSize = 10

    #Titulos de columna
    numero = Paragraph('''#''', styleBH)
    alumno = Paragraph(''' Alumno ''', styleBH)
    b1 = Paragraph(''' BIM1 ''', styleBH)
    b2 = Paragraph(''' BIM2 ''', styleBH)
    b3 = Paragraph(''' BIM3 ''', styleBH)
    total = Paragraph(''' TOTAL ''', styleBH)

    data = []
    #lista de la tabla con si
    #data.append = [[numero]]

    #tabla contenido
    styleN = styles["BodyText"]
    styleN.alignment = TA_CENTER
    styleN.fontSize = 7


    high = 650
    for student in students:
        this_student = [student['#'], student['name'], student['b1'], student['b2'], student['b3'], student['total']]
        data.append(this_student)
        high = high -18

    #escribir la tabla
    width, heigth = A4
    table = Table(data, colWidths = [1.9*cm, 9.5*cm, 1.9*cm, 1.9*cm, 1.9*cm, 1.9*cm])
    #Grilla de la tabla
    table.setStyle(TableStyle([
        ('INNERGRID', (0,0), (-1,-1), 0.25, colors.black),
        ('BOX',(0,0), (-1, -1), 0.25, colors.black), ]))

    #pdf size encapsularlo en el tamaño del A4 o tamaño de pagina
    table.wrapOn(c, width, heigth)
    table.drawOn(c, 30, high)
    c.showPage() #save page


    #guardar pdf
    c.save()
    #obtener valores de BytesIO del buffer y escribir en response
    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)
    #con el return descraga pdf
    return response
"""

templates/hello.html
{% extends "base.html" %}

{% block content %}
    <h1>Hello</h1>



    <h2>
        {% if user.is_authenticated %}
            <a href="{% url "userprofiles:logout" %}">logout</a>
            {{ user.username }}
        {% else %}
            <a href="{% url "userprofiles:authentication" %}">login</a>
        {% endif %}

    </h2>
{% endblock %}

templates/login-ss.html
{% extends "system_index.html" %}
{% block login_content %}
    <h1>Login</h1>
    <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="action" value="login">

        <input type="text" name="username">
        <input type="text" name="password">

        <button type="submit">Login</button>
    </form>
    
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html >
<head>
  {%load staticfiles%}
  <meta charset="UTF-8">
  <title>Login</title>
  
  
  
      <link rel="stylesheet" href="{% static "csslogin/style.css" %}">

  
</head>

<body>
  <!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">

    <title>Login</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
  </head>
    <h1>EL MAYORISTA </h1>
  <body class="align">

    <div class="grid">

      <form action="" method="post" class="form login">
        {% csrf_token %}

        <div class="form__field">
          <label for="login__username"><svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#user"></use></svg><span class="hidden">username</span></label>
          <input id="login__username" type="text" name="username" class="form__input" placeholder="Nombre de usuario" required>
        </div>

        <div class="form__field">
          <label for="login__password"><svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#lock"></use></svg><span class="hidden">password</span></label>
          <input id="login__password" type="password" name="password" class="form__input" placeholder="Contraseña" required>
        </div>
        <div class="form__field">
          <input type="submit" name="action" value="login">
        </div>

      </form>
      <p class="text--center">¿Te extraviaste? <a href="{% url 'usuario:index' %}">Regresa con nosotros</a> <svg class="icon"></svg></p>



    </div>
    
    <svg xmlns="http://www.w3.org/2000/svg" class="icons"><symbol id="arrow-right" viewBox="0 0 1792 1792"><path d="M1600 960q0 54-37 91l-651 651q-39 37-91 37-51 0-90-37l-75-75q-38-38-38-91t38-91l293-293H245q-52 0-84.5-37.5T128 1024V896q0-53 32.5-90.5T245 768h704L656 474q-38-36-38-90t38-90l75-75q38-38 90-38 53 0 91 38l651 651q37 35 37 90z"/></symbol><symbol id="lock" viewBox="0 0 1792 1792"><path d="M640 768h512V576q0-106-75-181t-181-75-181 75-75 181v192zm832 96v576q0 40-28 68t-68 28H416q-40 0-68-28t-28-68V864q0-40 28-68t68-28h32V576q0-184 132-316t316-132 316 132 132 316v192h32q40 0 68 28t28 68z"/></symbol><symbol id="user" viewBox="0 0 1792 1792"><path d="M1600 1405q0 120-73 189.5t-194 69.5H459q-121 0-194-69.5T192 1405q0-53 3.5-103.5t14-109T236 1084t43-97.5 62-81 85.5-53.5T538 832q9 0 42 21.5t74.5 48 108 48T896 971t133.5-21.5 108-48 74.5-48 42-21.5q61 0 111.5 20t85.5 53.5 62 81 43 97.5 26.5 108.5 14 109 3.5 103.5zm-320-893q0 159-112.5 271.5T896 896 624.5 783.5 512 512t112.5-271.5T896 128t271.5 112.5T1280 512z"/></symbol></svg>

  </body>

</html>
  
  
</body>
</html>

templates/productos.html
<h1>pro</h1>

templates/system_index.html
<!DOCTYPE HTML>
<!--
	Prologue by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		{%load staticfiles%}
		<title>Sistema</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets2/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="{% static "css2/main.css"%}" />
		<!--<link rel="stylesheet" href="assets/css/main.css" />   -->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets2/css/ie8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets2/css/ie9.css" /><![endif]-->
		{% block css %}{% endblock css %}
	</head>
	<body>

		<!-- Header -->
			<div id="header">

				<div class="top">

					<!-- Logo -->
						<div id="logo">
							<span class="image avatar48"><img src="images2/avatar.jpg" alt="" /></span>
							<h1 id="title">{{ user.username }}</h1>
							<p>grupo</p>
						</div>

					<!-- Nav -->
						<nav id="nav">

							<ul>

								<li><a href="{% url 'usuario:system_index' %}" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-home">Inicio</span></a></li>
								{% if not user.perfil %}
								<li><a href="{% url 'usuario:perfil_insert' %}" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-user">Perfil</span></a></li>
								{%endif%}
								<li><a href="{% url 'usuario:perfil_list' %}" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-user">Ver Perfil</span></a></li>


								<li><h4>----Inventario-----</h4></li>
								<li><a href="{% url 'inventario:inventario_list' %}" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-check-square">Listar</span></a></li>
								<li><a href="{% url 'inventario:inventario_insert' %}" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-save">Nuevo</span></a></li>

								<li><h4>---Proveedores----</h4></li>
								<li><a href="{% url 'proveedor:proveedor_list' %}" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-check-square">Listar</span></a></li>
								<li><a href="{% url 'proveedor:proveedor_insert' %}" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-save">Nuevo</span></a></li>

								<li><h4>---Clientes----</h4></li>
								<li><a href="{% url 'cliente:cliente_list' %}" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-check-square">Listar</span></a></li>
								<li><a href="{% url 'cliente:cliente_insert' %}" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-save">Nuevo</span></a></li>


								<li><h4>----Cotizar-----</h4></li>
								<li><a href="#top" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-check-square">Listar</span></a></li>
								<li><a href="#top" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-save">Nuevo</span></a></li>

								<li><h4>----Ventas-----</h4></li>
								<li><a href="{%url 'factura:factura_list'%}" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-check-square">Listar</span></a></li>
								<li><a href="{%url 'factura:factura_insert'%}" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-save">Nuevo</span></a></li>
								<li><a href="{%url 'factura:detalle_factura_insert' %}" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-save">Detalle</span></a></li>


								<li><h4>---Salir---</h4></li>
								<li><a href="{%url 'usuario:logout'%}" id="contact-link" class="skel-layers-ignoreHref"><span class="icon fa-sign-out">log Out</span></a>
								</li>

							</ul>
						</nav>

				</div>

				<div class="bottom">

					<!-- Social Icons -->
						<ul class="icons">
							<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
							<li><a href="#" target="_blank" class="icon fa-instagram"><span class="label">Facebook</span></a></li>

						</ul>

				</div>

			</div>

		<!-- Main -->
			<div id="main">

				<!-- Intro -->
					<section id="top" class="one dark cover">
						<div class="container">
							<header>
								<center><h2 class="alt">El Mayorista</h2>
								<p>Sistema contable.</p>
							</header>
						</div>
					</section>
					<!-- SISTEMA CONTABLE  -->
					<section id="sistema" class="two" >
						<div class="container">
							{% block system_Contable %}
							{%endblock%}
						</div>
					</section>

			</div>







		<!-- Footer -->
			<div id="footer">

				<!-- Copyright -->
					<ul class="copyright">
						<li>&copy; Untitled. All rights reserved.</li><li>Dev: <a href="http://rafaelromario.com">Rafael Romario</a></li>
					</ul>

			</div>

		<!-- Scripts

			<script src="{% static "js2/DjangoAjax.js"%}"></script>

			<script src="{% static "js2/jquery.min.js"%}"></script>
			<script src="{% static "js2/jquery.scrolly.min.js"%}"></script>
			<script src="{% static "js2/jquery.scrollzer.min.js"%}"></script>
			<script src="{% static "js2/skel.min.js"%}"></script>
			<script src="{% static "js2/util.js"%}"></script>
			<script src="{% static "js2/main.js"%}"></script>-->
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->

			<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" ></script>
			<script type="text/javascript" src="{% static "js2/ajax.js" %}"></script>
			<!--{% block js %}
			{% endblock %}-->

	</body>
</html>