cliente/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [#cambiar url logout
	url(r'^cliente/new', views.ClienteInsert.as_view(),
		name= "cliente_insert"),
	url(r'^cliente/list$', views.ClienteList.as_view(),
		name='cliente_list'),
	url(r'^cliente/edit(?P<pk>[0-9]+)/$',views.ClienteUpdate.as_view(),
		name='cliente_edit'),
	url(r'^cliente/delete(?P<pk>[0-9]+)/$', views.ClienteDelete.as_view(),
	 	name="cliente_delete"),
	url(r'^cliente/(?P<pk>[0-9]+)/$', views.cliente_detail, 
		name="cliente_detail"),




]

inventario/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [#cambiar url logout
	url(r'^inventario/new', views.InventarioInsert.as_view(), 
		name="inventario_insert"),
	url(r'^inventario/list$', views.InventarioList.as_view(), 
		name='inventario_list'),
	url(r'^inventario/edit(?P<pk>[0-9]+)/$', views.InventarioUpdate.as_view(), 
    	name='inventario_edit'),
	 url(r'^inventario/delete(?P<pk>[0-9]+)/$', views.InventarioDelete.as_view(),
	 	name="inventario_delete"),
	url(r'^inventario/(?P<pk>[0-9]+)/$', views.inventario_detail, 
		name="inventario_detail"),
]

plataforma/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('usuario.urls', namespace='usuario')),
    url(r'^', include('proveedor.urls', namespace='proveedor')),
    url(r'^', include('inventario.urls', namespace='inventario')),
    url(r'^', include('cliente.urls', namespace = 'cliente')),
    url(r'^', include('factura.urls', namespace = 'factura')),


]

inventario/models.py
from __future__ import unicode_literals
from django.db.models import signals
from django.db import models
from proveedor.models import Proveedor
import decimal
from django.db.models import signals

TAX_VALUE = 0.18
GANANCIA = 1.40

class Inventario(models.Model):
	codigo = models.CharField(max_length=25, unique=True)
	elemento = models.CharField(max_length=25, unique=True)
	cantidad = models.PositiveSmallIntegerField()
	descripcion = models.CharField(max_length=45)
	valorCompra = models.DecimalField(max_digits=7,
		decimal_places=2, default=0.00)
	valorIva = models.DecimalField(max_digits=6,
		decimal_places=2, default=0.00)
	valorVenta = models.DecimalField(max_digits=7, decimal_places=2, default=0.00)

	def __unicode__(self):
		return self.elemento

	def preciototal(self):
		precioTotal = self.valorCompra*self.cantidad
		return precioTotal


	def save(self, *args, **kwargs):
		if self.valorCompra:
			self.valorVenta = round(float(self.valorCompra)* GANANCIA, 3)
			self.valorIva = round(float(self.valorVenta) * TAX_VALUE, 3)
			super(Inventario, self).save(*args, **kwargs)
		else:
			self.valorIva=0
			super(Inventario, self).save(*args, **kwargs)

inventario/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
# Create your views here.
from .models import Inventario

from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    UpdateView,
    CreateView,
    DeleteView
    )
from django.core.urlresolvers import reverse_lazy

#mixins
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required


class InventarioInsert(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
	permission_required = ('inventario.add_inventario')
	model = Inventario
	success_url = reverse_lazy('inventario:inventario_list')
	fields = ['codigo', 'elemento', 'cantidad', 'descripcion',
	 'valorCompra', ]
	"""
	def calcular_precio_venta(self, form):
		print (valorCompra)
		form.instance.elemento = "platico"
	 	form.instance.valorVenta = 200
	 	return super(InventarioInsert, self).calcular_precio_venta(form)

"""

class InventarioList(LoginRequiredMixin, ListView):
    #permission_required = ('inventario.add_inventario')
    model = Inventario
    context_object_name = 'elementos'

class InventarioUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = ('inventario.change_inventario')
    model = Inventario
    success_url = reverse_lazy('inventario:inventario_list')
    fields = ['codigo', 'elemento', 'cantidad', 'descripcion',
              'valorCompra', 'valorIva', 'valorVenta']

class InventarioDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
	permission_required= ('inventario.delete_inventario')
	model = Inventario
	success_url = reverse_lazy('inventario:inventario_list')


@login_required()
def inventario_detail(request, pk):
    inventario = get_object_or_404(Inventario, pk=pk)
    template = loader.get_template('inventario/inventario_detail.html')
    context = {
        'inventario' : inventario
    }
    return HttpResponse(template.render(context, request))

templates/inventario/inventario_confirm_delete.html
{% extends "system_index.html" %}

{% block system_Contable %}

<form method="post">
	{% csrf_token %}
    ¿Estás seguro que deseas borrar el curso "{{ object }}"?
    <input type="submit" value="Borrar" />
</form>

{%endblock%}

templates/inventario/inventario_detail.html
{% extends "system_index.html" %}

{% block system_Contable %}
<a href="{%url 'inventario:inventario_list' %}"><span class="icon fa-arrow-left "></span></a>
	<ul>
	<li><b>Codigo: </b>{{inventario.codigo}}</li>
	<li><b>Elemento: </b>{{inventario.elemento}}</li>
	<li><b>Cantidad: </b>{{inventario.cantidad}}</li>
	<li><b>Descripción: </b>{{inventario.descripcion}}</li>
	<li><b>Valor Compra: </b>{{inventario.valorCompra}}</li>
	<li><b>Valor Iva: </b>{{inventario.valorIva}}</li>
	<li><b>Valor Venta: </b>{{inventario.valorVenta}}</li>
	</ul>
	
{%endblock%}

templates/inventario/inventario_form.html
{% extends "system_index.html" %}

{% block system_Contable %}
<form method="post">
	<header>
        <h2>Elemento </h2>
    </header>
   
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" />
</form>
{%endblock%}

templates/inventario/inventario_list.html
{% extends "system_index.html" %}

{% block system_Contable %}


<table id="example1" class="table table-bordered table-striped">
    
    <thead>
        <tr>

            <th>Codigo</th>                                      
            <th>Elemento</th> 
            <th>Stock</th>                              
            <th>valor Iva</th>
            <th>valor Venta</th>
            <th></th>
            <th></th>                         
        </tr>
    </thead>
    <tbody>
    	{% for pr in elementos %}
    		<tr>
    			<td>{{pr.codigo}}</td>
    			<td>{{pr.elemento}}</td>
    			<td>{{pr.cantidad}}</td>
    			<td>{{pr.valorIva}}</td>
    			<td>{{pr.valorVenta}}</td>
				<td><a href="{% url 'inventario:inventario_detail' pr.id %}"><span class="icon fa-eye "></span></a>
				<a href="{%url 'inventario:inventario_edit' pr.id %}"><span class="icon fa-pencil-square-o"></span></a>
				<a href="{%url 'inventario:inventario_delete' pr.id %}"><span class="icon fa-trash"></span></a></td>
    		</tr>
    	{% endfor %}
    </tbody>	

</table>

{%endblock%}